#!/usr/bin/env bash
set -x
set -e

source /common.sh

apt-get update

# Install required packages
apt-get install -y libopenal-dev libopus-dev libasound2-dev ffmpeg

# TODO: Download and install raspicom binary

apt-get clean
apt-get autoremove -y
