#!/usr/bin/env bash
set -x
set -e

source /common.sh

apt-get update

tar -C /usr/local -xzf go1.15.2.linux-amd64.tar.gz
echo 'export PATH=$PATH:/usr/local/go/bin' > /etc/profile

apt-get clean
apt-get autoremove -y
