#!/usr/bin/env bash
set -x
set -e

source /common.sh

apt-get update

# Configure soundcard
echo "dtoverlay=$SOUNDCARD" >> /boot/config.txt
cat <<EOT >> /etc/asound.conf
pcm.!default {
  type plug
  slave.pcm "hw:0,0"
}
ctl.!default {
  type hw card 0
}
EOT

# Install required packages
apt-get install -y libopenal-dev libopus-dev libasound2-dev ffmpeg git vim

# Install Go
curl -L -o go.tar.gz https://golang.org/dl/go$GO_VERSION.linux-armv6l.tar.gz
tar -C /usr/local -xzf go.tar.gz
echo 'export PATH=$PATH:/usr/local/go/bin' > /etc/profile
source /etc/profile
go env
export GOROOT=/usr/local/go

# Install mumbli
go get -u github.com/joneug/mumbli

apt-get clean
apt-get autoremove -y
